from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('voluntariado.views',
	url(r'^main/$', 'main_view'),
	url(r'^nuevaorg/$', 'ingreso_ong'),
	url(r'^nuevovoluntario/$', 'ingreso_voluntario'),
	url(r'^nuevaempresa/$', 'ingreso_empresa'),
	url(r'^voluntario/(\d+)/$', 'volunteer_profile'),
	url(r'^(voluntario)/(\d+)/buscar_empleo/$', 'match_search'),
	url(r'^empresa/(\d+)/$', 'ong_profile'), #TODO perfil de empresa
	url(r'^(empresa)/(\d+)/buscar_empleo/$', 'match_search'),
	url(r'^ong/(\d+)/$', 'ong_profile'),
	url(r'^ong/(\d+)/nuevoproyecto/$', 'nuevo_proyecto'),
	url(r'^proyecto/(\d+)/$', 'proyecto'),
	url(r'^proyecto/(\d+)/nuevopuesto/$', 'nuevo_puesto'),
	url(r'^puesto/(\d+)/$', 'puesto'),
	url(r'^(puesto)/(\d+)/buscar_voluntarios/$', 'match_search'),
	url(r'^linkedin/$','linkedin'),
	url(r'^home/voluntario/$','home_voluntario'),
	url(r'^home/ong/$','home_ong'),
	url(r'^home/empresa/$','home_empresa'),
	url(r'^logout/$','logout_view'),
	url(r'^editarvoluntario/$','edit_volunteer'),
	url(r'^editarong/$','edit_ong'),
	url(r'^puesto/(\d+)/voluntario/(\d+)/$', 'puesto_voluntario'),
)
